#!/usr/bin/env bash
# AFK-Runner: nimmt das aelteste freie ready-for-agent-Ticket von der Frontier,
# arbeitet es in einem isolierten Git-Worktree per Claude Code (headless) ab,
# pusht den Ticket-Branch und oeffnet einen Pull Request als Checkpoint.
# Ein Aufruf = ein Ticket (ralph-once-Prinzip). Mehrere Laeufe: afk-loop.sh.
#
# Exit-Codes: 0 = PR offen · 1 = Lauf gescheitert · 3 = Frontier leer
set -euo pipefail
cd "$(dirname "$0")/.."

REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)

# ── 1. Frontier: aeltestes offenes ready-for-agent-Ticket ohne offene
#      Blocker (native Issue-Dependencies) und ohne Assignee ────────────────
NUM=""
for n in $(gh issue list --label ready-for-agent --state open \
  --json number --jq 'sort_by(.number) | .[].number'); do
  info=$(gh api "repos/$REPO/issues/$n" \
    --jq '[(.issue_dependencies_summary.blocked_by // 0), (.assignees | length)] | @tsv')
  blocked=$(echo "$info" | cut -f1)
  assigned=$(echo "$info" | cut -f2)
  if [ "$blocked" = "0" ] && [ "$assigned" = "0" ]; then NUM=$n; break; fi
done
if [ -z "$NUM" ]; then
  echo "Frontier leer — kein freies ready-for-agent-Ticket."
  exit 3
fi

TITLE=$(gh issue view "$NUM" --json title --jq .title)
BRANCH="ticket/$NUM"
WT="../profilierer-afk/issue-$NUM"
echo "== Ticket #$NUM: $TITLE"
echo "== Branch $BRANCH, Worktree $WT"

# ── 2. Claim (verhindert Doppel-Zugriff paralleler Laeufe) ─────────────────
gh issue edit "$NUM" --add-assignee "@me" >/dev/null

# ── 3. Isolierter Worktree ab aktuellem main ───────────────────────────────
git fetch -q origin main
git worktree add "$WT" -b "$BRANCH" origin/main
trap 'git worktree remove "$WT" --force 2>/dev/null || true' EXIT

# ── 4. Abhaengigkeiten (eigene node_modules je Worktree) ───────────────────
(cd "$WT" && npm ci --silent && npm ci --prefix server --silent)

# ── 5. Claude Code headless — committet, pusht aber nicht (Hook sperrt
#      main-Push ohnehin; den Branch-Push macht der Runner) ────────────────
PROMPT="Arbeite GitHub-Issue #$NUM dieses Repos vollstaendig ab.
Lies zuerst das Issue samt Kommentaren (gh issue view $NUM --comments) und
die dort referenzierte Spec. Arbeite testgetrieben an den im Issue genannten
Naehten (Skill /tdd). Halte dich an docs/contributing.md und CLAUDE.md.
Fahre am Ende npm run check — es muss gruen sein. Committe deine Arbeit auf
den aktuellen Branch (knappe deutsche Commit-Nachricht mit Praefix).
Pushe nicht und oeffne keinen PR — das uebernimmt der Runner."
(cd "$WT" && claude -p "$PROMPT" --permission-mode acceptEdits)

# ── 6. Verifikation: Commit vorhanden + Pruefkette gruen ───────────────────
if [ -z "$(git -C "$WT" log origin/main..HEAD --oneline)" ]; then
  echo "!! Kein Commit entstanden — Ticket bleibt zugewiesen, bitte ansehen."
  exit 1
fi
(cd "$WT" && npm run check)

# ── 7. Checkpoint: Branch pushen, PR oeffnen, Issue vermerken ──────────────
git -C "$WT" push -u origin "$BRANCH"
gh pr create --head "$BRANCH" --title "$TITLE" --body "$(printf 'Closes #%s — AFK-Lauf vom %s. Vor dem Merge reviewen.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)' "$NUM" "$(date +%y.%m.%d)")"
gh issue comment "$NUM" --body "> *This was generated by AI during an AFK run.*

PR ist offen, CI läuft. Review vor Merge."

echo "== Fertig: PR fuer #$NUM offen."
