#!/usr/bin/env bash
# AFK-Runner: nimmt das aelteste freie ready-for-agent-Ticket von der Frontier,
# arbeitet es in einem isolierten Git-Worktree per Claude Code (headless) ab,
# pusht den Ticket-Branch und oeffnet einen Pull Request als Checkpoint.
# Ein Aufruf = ein Ticket (ralph-once-Prinzip). Mehrere Laeufe: afk-loop.sh.
#
# Exit-Codes: 0 = PR offen · 1 = Lauf gescheitert · 3 = Frontier leer
set -euo pipefail
cd "$(dirname "$0")/.."

REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)

# ── 1. Frontier: aeltestes offenes ready-for-agent-Ticket ohne offene
#      Blocker (native Issue-Dependencies) und ohne Assignee ────────────────
NUM=""
for n in $(gh issue list --label ready-for-agent --state open \
  --json number --jq 'sort_by(.number) | .[].number'); do
  info=$(gh api "repos/$REPO/issues/$n" \
    --jq '[(.issue_dependencies_summary.blocked_by // 0), (.assignees | length)] | @tsv')
  blocked=$(echo "$info" | cut -f1)
  assigned=$(echo "$info" | cut -f2)
  if [ "$blocked" = "0" ] && [ "$assigned" = "0" ]; then NUM=$n; break; fi
done
if [ -z "$NUM" ]; then
  echo "Frontier leer — kein freies ready-for-agent-Ticket."
  exit 3
fi

TITLE=$(gh issue view "$NUM" --json title --jq .title)
BRANCH="ticket/$NUM"
WT="../profilierer-afk/issue-$NUM"
echo "== Ticket #$NUM: $TITLE"
echo "== Branch $BRANCH, Worktree $WT"

# ── 2. Claim (verhindert Doppel-Zugriff paralleler Laeufe) ─────────────────
gh issue edit "$NUM" --add-assignee "@me" >/dev/null

# ── 3. Isolierter Worktree ab aktuellem main ───────────────────────────────
git fetch -q origin main
git worktree add "$WT" -b "$BRANCH" origin/main
trap 'git worktree remove "$WT" --force 2>/dev/null || true' EXIT

# ── 4. Abhaengigkeiten (eigene node_modules je Worktree) ───────────────────
(cd "$WT" && npm ci --silent && npm ci --prefix server --silent)

# ── 5. Claude Code headless — committet, pusht aber nicht (Hook sperrt
#      main-Push ohnehin; den Branch-Push macht der Runner) ────────────────
PROMPT="Arbeite GitHub-Issue #$NUM dieses Repos vollstaendig ab.
Lies zuerst das Issue samt Kommentaren (gh issue view $NUM --comments) und
die dort referenzierte Spec. Arbeite testgetrieben an den im Issue genannten
Naehten (Skill /tdd). Halte dich an docs/contributing.md und CLAUDE.md.
Fahre am Ende npm run check — es muss gruen sein. Committe deine Arbeit auf
den aktuellen Branch (knappe deutsche Commit-Nachricht mit Praefix).
Pushe nicht und oeffne keinen PR — das uebernimmt der Runner."
(cd "$WT" && claude -p "$PROMPT" --permission-mode acceptEdits)

# ── 6. Verifikation: Commit vorhanden + Pruefkette gruen ───────────────────
if [ -z "$(git -C "$WT" log origin/main..HEAD --oneline)" ]; then
  echo "!! Kein Commit entstanden — Ticket bleibt zugewiesen, bitte ansehen."
  exit 1
fi
(cd "$WT" && npm run check)

# ── 7. Checkpoint: Branch pushen, PR oeffnen, Issue vermerken ──────────────
git -C "$WT" push -u origin "$BRANCH"
gh pr create --head "$BRANCH" --title "$TITLE" --body "$(printf 'Closes #%s — AFK-Lauf vom %s.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)' "$NUM" "$(date +%y.%m.%d)")"
gh issue comment "$NUM" --body "> *This was generated by AI during an AFK run.*

PR ist offen, CI läuft."

# ── 8. Review-Agent: frischer Kontext, sieht nur Ticket + Diff ─────────────
#      Nach Matts Pipeline (Implementer -> Reviewer -> Merger): der Reviewer
#      hat die Implementierung nicht gebaut und laeuft ohne Schreibrechte
#      (Default-Permission-Mode — Edits scheitern, Lesen und die
#      allowlisteten git/gh-Lesebefehle funktionieren).
PR=$(gh pr view "$BRANCH" --json number --jq .number)
REVIEW_PROMPT="Du bist Code-Reviewer mit frischem Kontext — du hast diese
Aenderung nicht geschrieben. Pruefe den Diff dieses Branches gegen origin/main
(git diff origin/main...HEAD) gegen das Ticket #$NUM (gh issue view $NUM
--comments) und die dort referenzierte Spec.

Pruefkriterien, in dieser Reihenfolge:
1. Erfuellt der Diff das Ticket vollstaendig — nichts fehlt, nichts darueber hinaus?
2. Fachliche Fehler, Randfaelle, kaputte Invarianten (docs/contributing.md:
   neue Referenzen bei Store-Mutationen, SVG-Klassen, noUncheckedIndexedAccess)?
3. Decken die neuen Tests die im Ticket genannten Naehte, testen sie Verhalten
   statt Implementierung?
4. Konventionen: deutsche Bezeichner, keine ungefragten Refactors, Commit-Stil.

Antworte mit deinen Befunden (knapp, nummeriert, mit Datei:Zeile). Die LETZTE
Zeile deiner Antwort muss exakt lauten:
VERDICT: MERGE   (keine blockierenden Befunde)
oder
VERDICT: HUMAN   (mindestens ein Befund braucht menschliches Urteil)
Im Zweifel HUMAN."
REVIEW=$(cd "$WT" && claude -p "$REVIEW_PROMPT" --model opus 2>&1) || true
gh pr comment "$PR" --body "$(printf '> *This was generated by AI during an AFK run (Review-Agent, frischer Kontext).*\n\n%s' "$REVIEW")"

# ── 9. Merger: nur bei VERDICT MERGE und gruenem CI (AFK_AUTO_MERGE=0
#      schaltet auf reinen Mensch-Review um). Geflaggte PRs bleiben offen,
#      der Loop macht mit dem naechsten freien Ticket weiter (Exit 2).
if [ "${AFK_AUTO_MERGE:-1}" != "1" ]; then
  echo "== Fertig: PR #$PR offen (Auto-Merge aus, Review-Kommentar liegt an)."
  exit 0
fi
if ! printf '%s' "$REVIEW" | tail -1 | grep -q "VERDICT: MERGE"; then
  echo "== Review-Agent flaggt PR #$PR fuer menschliches Review — bleibt offen."
  exit 2
fi
echo "== Warte auf CI fuer PR #$PR …"
if ! gh pr checks "$PR" --watch --fail-fast; then
  echo "!! CI rot — PR #$PR bleibt zum Ansehen offen."
  exit 1
fi
gh pr merge "$PR" --rebase --delete-branch
git branch -d "$BRANCH" 2>/dev/null || true
echo "== Fertig: PR #$PR gemergt, Issue #$NUM geschlossen."
